### ISSUE TITLE
CMC values

### ISSUE THREAD

**Issue by Anubhople** [LinShanify/CMC#1]
Hello sir, can you please tell me how can i get those cmc values.

**Comment by LinShanify** [comment]
cmc values is calculated from the corresponding re-id algorithms. I just give an example here.

**Comment by Anubhople** [comment]
Thank you so much
one more query, can i get those CMC values by calculating rank1 , rank2...... accuracies

**Comment by LinShanify** [comment]
yes. cmc values are the list of rank1 , rank2...... accuracies. I just copy-pasted from someone's paper (I forgot).

**Comment by Anubhople** [comment]
Okay thank you so much!!
